apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bacalhau
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bacalhau
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-bacalhau
    spec:
      containers:
        - name: bacalhau
          image: "{{ .Values.bacalhau.image.repository }}:{{ .Values.bacalhau.image.tag }}"
          args: {{ .Values.bacalhau.args | toYaml | nindent 12 }}
          env: {{ .Values.bacalhau.environment | toYaml | nindent 12 }}
          volumeMounts:
            - name: bacalhau-data
              mountPath: /root/.bacalhau
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: bacalhau-data
          persistentVolumeClaim:
            claimName: bacalhau-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
