apiVersion: v1
kind: Service
metadata:
  name: ipfs
spec:
  selector:
    app: ipfs
  ports:
    {{- range .Values.ipfs.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      name: {{ .name }}
    {{- end }}
