{{- if .Values.ipfs.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.ipfs.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.ipfs.persistence.size }}
---
{{- end }}
{{- if .Values.bacalhau.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bacalhau-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.bacalhau.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.bacalhau.persistence.size }}
---
{{- end }}
{{- if .Values.resourceProvider.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lilypad-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.resourceProvider.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.resourceProvider.persistence.size }}
{{- end }}
