bacalhau:
  image:
    repository: ghcr.io/lilypad-tech/bacalhau
    tag: latest
  environment:
    - name: BACALHAU_ENVIRONMENT
      value: local
  args:
    - serve
    - --node-type
    - compute,requester
    - --peer
    - none
    - --private-internal-ipfs=false
    - --job-selection-accept-networked
    - --ipfs-connect
    - /dns4/ipfs/tcp/5001
  persistence:
    enabled: true
    storageClass: ""
    size: 10Gi

resourceProvider:
  image:
    repository: ghcr.io/lilypad-tech/resource-provider
    tag: latest
  environment:
    - name: WEB3_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: lilypad-secrets
          key: WEB3_PRIVATE_KEY
    - name: WEB3_RPC_URL
      valueFrom:
        secretKeyRef:
          name: lilypad-secrets
          key: RPC
    - name: IPFS_CONNECT
      value: /dns4/ipfs/tcp/5001
    # TODO: Place into templates using Bacalhau service definition
    - name: BACALHAU_API_HOST
      value: lilypad-bacalhau.default.svc.cluster.local
    - name: BACALHAU_NODE_CLIENTAPI_HOST
      value: lilypad-bacalhau.default.svc.cluster.local
    - name: BACALHAU_NODE_CLIENTAPI_PORT
      value: "1234"
  persistence:
    enabled: true
    storageClass: ""
    size: 10Gi

watchtower:
  image:
    repository: containrrr/watchtower
    tag: latest
